---
- name: create service for deployment
  hosts: kubeadmin
  become: true
  user: root

  tasks:
  - name: create a service
    command: kubectl apply -f /var/lib/jenkins/workspace/repo-clone/Kubernetes/valaxy-service.yml

