apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: valaxy-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the templat
  template:
    metadata:
      labels:
        app: valaxy
    spec:
      containers:
      - name: valaxy-devops-project
        image: ijazu/hello
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
