apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: valaxy
spec:
  selector:
    app: valaxy
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30088
